### PR TITLE
[Readme timings] Add timings to readme.md 

### PR DESCRIPTION
**Pull request by lrnv**
Is the "up to 1000x LOC" and "up to 50x perf" realistic ?

### CODE REVIEW

**Comment by rimhajal** [comment]
This is also mentioned in the docs, do I remove it from there as well?

**Comment by lrnv** [comment]
remove no, correct yes. What is the true perf gain on your machine ? What is the real number of LOC of relsurv for the same functionlities ?

**Comment by lrnv** [comment]
I linked the issue w.r.t. timings so that it will happen in this branch.

**Comment by lrnv** [comment]
So this version should be very good. Timings on my machine are in the readme, would you mind running them on your machine and switching if they are better ?

**Comment by lrnv** [comment]
@rimhajal for me this is good to go after you replaced the numbers with the ones from your computer

**Comment by lrnv** [comment]
@rimhajal I like those timings. if you agree this could be merged too ?

**Pull request merged**
